# Generated by Django 5.0.2 on 2024-02-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_info', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_pefernce', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
