# Generated by Django 5.0.2 on 2024-02-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0002_vehiclemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
