# Generated by Django 5.0.2 on 2024-02-10 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0005_alter_userdetails_created_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=200, null=True)),
                ('toll_amt', models.FloatField(blank=True, null=True)),
                ('valid_dt', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 4, 24, 31, 913347), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 4, 24, 31, 914344), null=True),
        ),
    ]
