# Generated by Django 5.0.2 on 2024-02-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0006_tollinfo_alter_userdetails_created_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollinfo',
            name='valid_dt',
        ),
        migrations.AddField(
            model_name='tollinfo',
            name='valid_toll_hr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 8, 14, 20, 899109), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 8, 14, 20, 900108), null=True),
        ),
    ]
