# Generated by Django 5.0.2 on 2024-02-13 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0009_tollcollection_addr_tollcollection_lane_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollcollection',
            name='lane',
        ),
        migrations.RemoveField(
            model_name='tollcollection',
            name='toll_calculation',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 9, 30, 39, 73371), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 9, 30, 39, 73371), null=True),
        ),
    ]
