# Generated by Django 3.2.24 on 2024-02-15 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0013_alter_userdetails_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 8, 42, 11, 8756), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 8, 42, 11, 9755), null=True),
        ),
    ]
