# Generated by Django 5.0.2 on 2024-03-03 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0016_alter_userdetails_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrequest',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 46, 44, 839617), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 46, 44, 836619), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 46, 44, 837619), null=True),
        ),
    ]
