# Generated by Django 5.0.2 on 2024-03-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0017_passwordrequest_created_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordrequest',
            old_name='user_id',
            new_name='fk_user',
        ),
        migrations.AddField(
            model_name='passwordrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordrequest',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 50, 3, 990705), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 50, 3, 988707), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 20, 50, 3, 988707), null=True),
        ),
    ]
