# Generated by Django 5.0.2 on 2024-03-03 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0018_rename_user_id_passwordrequest_fk_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordrequest',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 22, 37, 53, 679199), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 22, 37, 53, 676200), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 22, 37, 53, 677202), null=True),
        ),
    ]
