# Generated by Django 5.0.2 on 2024-03-03 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpms_app', '0019_userdetails_status_alter_passwordrequest_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollcollection',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 23, 24, 18, 733429), null=True),
        ),
        migrations.AlterField(
            model_name='passwordrequest',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 23, 24, 18, 734428), null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 23, 24, 18, 732430), null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 3, 23, 24, 18, 732430), null=True),
        ),
    ]
